[package]
name = "atomic_store"
version = "0.1.0"
authors = ["Nathan F Yospe <nathan@translucence.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.0"
chrono = "0.4.19"
glob = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
snafu = { version = "0.6.10", features = ["backtraces"] }
