[package]
name = "atomic_store"
description = "Persistence with atomic synchronization for a single version of record"
version = "0.0.2"
authors = ["Nathan F Yospe <nathan@translucence.net>"]
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-serialize = { version = "0.3.0", default-features = false }
bincode = "1.3.3"
chrono = "0.4.19"
glob = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
snafu = { version = "0.6.10", features = ["backtraces"] }

[dev-dependencies]
array-init = "2.0.0"
