name: Build

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Outdated Builds
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4
        name: Checkout Repository

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching
        with:
          cache-on-failure: true

      - name: Format Check
        run: cargo fmt -- --check

      - name: Lint
        run: |
          cargo clippy -- -D warnings

      - name: Audit
        run: cargo audit --ignore RUSTSEC-2023-0018

      - name: Build
        run: cargo build --release --examples

      - name: Test
        run: cargo test --release --all-features -- -Zunstable-options --report-time

      - name: Generate Documentation
        run: |
          cargo doc --no-deps --document-private-items -p atomic_store
          cp -R target/doc public
          echo '<meta http-equiv="refresh" content="0; url=atomic_store">' > public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: atomicstore.docs.espressosys.com
