name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: registry.gitlab.com/asuran-rs/containers/rust-sccache-docker:1.56
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - name: Configure Git
        run: |
          git config --global url."https://tl-ancients:${{ secrets.GITLAB_PAT }}@gitlab.com/".insteadOf git://gitlab.com
          git config --global url."https://tl-ancients:${{ secrets.GITLAB_PAT }}@gitlab.com/".insteadOf ssh://git@gitlab.com
          git config --global url."https://ancient123:${{ secrets.GITHUB_PAT }}@github.com/".insteadOf git://github.com
          git config --global url."https://ancient123:${{ secrets.GITHUB_PAT }}@github.com/".insteadOf ssh://git@github.com
          git config --global url."https://dl.cloudsmith.io/${{ secrets.CLOUDSMITH_ENTITLEMENT }}/".insteadOf https://dl.cloudsmith.io/basic/

      - uses: Swatinem/rust-cache@v1
        name: Enable Rust Caching

      - name: Format Check
        run: cargo fmt -- --check

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ github.token }}
          args: -- -D warnings

      - name: Check
        run: cargo check

      - name: Audit
        run: cargo audit --ignore RUSTSEC-2020-0159 --ignore RUSTSEC-2020-0071

      - name: Build
        run: cargo build --release --examples

      - name: Test
        run: cargo test --release --all-features -- -Zunstable-options --report-time

      - name: Generate Documentation
        run: |
          cargo doc --no-deps --document-private-items -p atomic_store
          cp -R target/doc public
          echo '<meta http-equiv="refresh" content="0; url=atomic_store">' > public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: atomicstore.docs.goespresso.com
