name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Outdated Builds
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        name: Checkout Repository

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: "1.56.1"
          override: true
          default: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching

      - name: Format Check
        run: cargo fmt -- --check

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ github.token }}
          args: -- -D warnings

      - name: Audit
        run: cargo audit

      - name: Build
        run: cargo build --release --examples

      - name: Test
        run: cargo test --release --all-features -- -Zunstable-options --report-time

      - name: Generate Documentation
        run: |
          cargo doc --no-deps --document-private-items -p atomic_store
          cp -R target/doc public
          echo '<meta http-equiv="refresh" content="0; url=atomic_store">' > public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: atomicstore.docs.espressosys.com
